name: .NET

on:
  push:
    branches: [main]
    paths:
      - "auth-service/**"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: "auth-service"
    steps:
      - uses: actions/checkout@v3
      #- name: Setup .NET
      #uses: actions/setup-dotnet@v2
      #with:
      #dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Test
        run: dotnet test --no-build --verbosity normal # <-- this is the current bottom line
      - name: Publish
        run: dotnet publish spider3auth/spider3auth.csproj -c Release
      - name: Deploy to IIS
        run: |
          iisreset /stop
          Copy-Item D:\actions-runner\_work\spiderauth\spiderauth\spider3auth\bin\Release\net6.0\publish D:\spiderauth -Recurse -Force
          iisreset /start
        ##############
